### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by Ashtor** [agilgur5/DeChat#1]
I went to the site http://dechat.github.io/ to download the extension,but it is impossible to download it.. the download doesnt work at all.. nothing. please make it work or remove it. no point have a site when it doesnt work.

**Comment by agilgur5** [comment]
Sorry for not ever responding, I apparently wasn't "watching" my own repos until [May 25th, 2017](https://github.com/agilgur5/react-signature-canvas/pull/1#issuecomment-303929061) and so only started getting notifications after then. Not sure why it didn't work (we used it quite heavily), possibly because the extension was/is unmaintained in the Chrome store or something.

In any case, this was a one-time project that was never followed up on (as evidenced by the huge TODO list and 0 commits since creation). After creating this, I also learned that there were several similar projects that were much farther ahead! Here's a short list taken from [`simple-peer`'s list of dependents](https://github.com/feross/simple-peer#who-is-using-simple-peer):
- [Friends](https://github.com/moose-team/friends), basically a decentralized Slack clone made by some folks who do (did?) a lot of decentralized browser projects
- [Peer Calls](https://peercalls.com/) - "WebRTC group video calling. Create a room. Share the link."
- [oorja.io](https://github.com/akshayKMR/oorja) - "Effortless video-voice chat with realtime collaborative features. Extensible using react components 🙌"
- [TalktoMe](https://talktome.space/) - "Skype alternative for audio/video conferencing based on WebRTC, but without the loss of packets."
- plenty more in the list and all around

Archiving this repo shortly
